"""Initial Migration4

Revision ID: 4992457b7a22
Revises: c85f93587e99
Create Date: 2022-03-16 15:37:30.218505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4992457b7a22'
down_revision = 'c85f93587e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'description')
    # ### end Alembic commands ###
