"""Initial Migration2

Revision ID: 869fc8c9e169
Revises: 715d76c86907
Create Date: 2022-03-16 13:24:34.466006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869fc8c9e169'
down_revision = '715d76c86907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allergy', sa.String(length=255), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('user', 'allergy')
    # ### end Alembic commands ###
