"""Initial Migration4

Revision ID: fa28f5ced5b5
Revises: 4992457b7a22
Create Date: 2022-03-16 21:37:48.972386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa28f5ced5b5'
down_revision = '4992457b7a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medicine', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medicine', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicine', type_='foreignkey')
    op.drop_column('medicine', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
